---
counterActIP: <ip-address> # EM / CT IP
Web-API:                  # WebAPI Settings 
    User: <username>      # Username of WebAPI 
    Password: <password>  # Password of WebAPI 
DEX-Web-Serivces:           # DEX Web Services Settings
    User: <name>@<username> # User of DEX Account in format: <name>@<username> 
    Password: <password>    # Password of DEX Account 
